name: npm

on:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mmoyaferrer/set-github-variable@v1.0.0
        with:
          name: 'SAMPLE_VAR'
          value: 'Hello World'
          repository: jintaeson/action
          token: ${{ secrets.TOKEN }}
