name: ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=RUBY_VERSION::$(cat .ruby-version)"
        id: rbenv

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
